language: python
python:
  - "2.7"
  - "3.4.3"
install:
  - "pip install coveralls"
  - "pip install -e .[test]"
script: 
  - py.test
  - coverage run --source=HBCTF -m py.test
after_success:
  - coveralls
sudo: false
notifications:
  slack: hackbama:zd8Y7CleJl3Nuepb5cKthS8p